// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let currentDirectoryPath = "/var/mobile/Library/Mobile Documents/iCloud~com~apple~Playgrounds/Documents/SparseBox.swiftpm"

let package = Package(
    name: "SparseBox",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SparseBox",
            targets: ["SparseBox"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "SparseBox",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ],
            linkerSettings: [
                .unsafeFlags([
                    //"-import-objc-header", "\(currentDirectoryPath)/minimuxer-Bridging-Header.h",
                    // Building in Swift Playgrounds, cannot use normal linking flow
                    "-rpath", "@executable_path",
                    "-rpath", "@executable_path/Frameworks",
                    "-L\(currentDirectoryPath)/Resources",
                    "-L/var/mobile/Containers/Data/PluginKitPlugin/2AED8E14-F306-4B6C-B736-2546CF7AD185/Documents",
                ]),
                .linkedLibrary("EMProxy"),
                .linkedLibrary("imobiledevice")
            ]
        )
    ]
)
