// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes
import Foundation

let currentDirectoryPath = "/var/mobile/Library/Mobile Documents/iCloud~com~apple~Playgrounds/Documents/SparseBox.swiftpm"
#if os(iOS)
let compilerAccessiblePath = "/var/mobile/Containers/Data/PluginKitPlugin/C7B10296-7E83-4753-9BF5-A3F9A7F800C7/Documents"
#else
let compilerAccessiblePath = FileManager.default.currentDirectoryPath
#endif

let package = Package(
    name: "SparseBox",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SparseBox",
            targets: ["SparseBox"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "SparseBox",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals"),
                .unsafeFlags([
                    "-I\(compilerAccessiblePath)/include",
                    "-import-objc-header",
                    "\(compilerAccessiblePath)/include/minimuxer-Bridging-Header.h",
                    "-import-objc-header",
                    "\(compilerAccessiblePath)/include/libimobiledevice-Bridging-Header.h",
                ]),
            ],
            linkerSettings: [
                .unsafeFlags([
                    // Building in Swift Playgrounds, cannot use normal linking flow
                    "-rpath", "@executable_path",
                    "-rpath", "@executable_path/Frameworks",
                    //"-L\(currentDirectoryPath)/Resources",
                    "-L\(compilerAccessiblePath)/Resources",
                ]),
                .linkedLibrary("EMProxy"),
                .linkedLibrary("imobiledevice")
            ]
        )
    ]
)
